package org.psk.lab.payment.util;

import org.psk.lab.payment.data.dto.PaymentDTO;
import org.psk.lab.payment.data.model.Payment;
import org.psk.lab.payment.data.model.PaymentStatus;

import java.time.LocalDateTime;
import java.util.UUID;

public class PaymentMapper {
    public static Payment toEntity(PaymentDTO dto) {
        return new Payment(
                null, // id will be generated by JPA
                UUID.fromString(dto.orderId()),
                dto.amount(),
                PaymentStatus.PENDING,
                LocalDateTime.now(),
                "pending_" + UUID.randomUUID().toString().substring(0, 8)
        );
    }

    public static PaymentDTO toDTO(Payment payment) {
        return new PaymentDTO(
                payment.getOrderId().toString(),
                payment.getAmount(),
                payment.getPaymentStatus(),
                payment.getTransactionId()
        );
    }
}